// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDARjuxrYCJ_lVx5vE1UY7s-wlZsxfYOQA',
    appId: '1:18034511862:web:b85b674ec96a45389ac1d7',
    messagingSenderId: '18034511862',
    projectId: 'flutter-auth-820a6',
    authDomain: 'flutter-auth-820a6.firebaseapp.com',
    storageBucket: 'flutter-auth-820a6.firebasestorage.app',
    measurementId: 'G-SXDN99Q3ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRV9QlC0QNBjR2Z-iJ1j_skf1MrKZ7Vnw',
    appId: '1:18034511862:android:890c624b66017f849ac1d7',
    messagingSenderId: '18034511862',
    projectId: 'flutter-auth-820a6',
    storageBucket: 'flutter-auth-820a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATVoVep3Vk9AUxmgNzL_RhVdEUqdoozP4',
    appId: '1:18034511862:ios:eb0b401a05ddb86c9ac1d7',
    messagingSenderId: '18034511862',
    projectId: 'flutter-auth-820a6',
    storageBucket: 'flutter-auth-820a6.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATVoVep3Vk9AUxmgNzL_RhVdEUqdoozP4',
    appId: '1:18034511862:ios:eb0b401a05ddb86c9ac1d7',
    messagingSenderId: '18034511862',
    projectId: 'flutter-auth-820a6',
    storageBucket: 'flutter-auth-820a6.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDARjuxrYCJ_lVx5vE1UY7s-wlZsxfYOQA',
    appId: '1:18034511862:web:c8488014284d85699ac1d7',
    messagingSenderId: '18034511862',
    projectId: 'flutter-auth-820a6',
    authDomain: 'flutter-auth-820a6.firebaseapp.com',
    storageBucket: 'flutter-auth-820a6.firebasestorage.app',
    measurementId: 'G-8TM54JJ9SQ',
  );
}
